In [1]:
# dependency package: https://github.com/KwiatLab/Quantum-Tomography
import QuantumTomography as qLib
import numpy as np

# Coincidence counts for 9 measurements, XX->ZZ, 4 detectors
coincidence_counts = np.array([[108,   3,   3,  86],
       [ 57,  43,  53,  47],
       [ 48,  50,  61,  41],
       [ 46,  46,  54,  54],
       [  1,  96, 101,   2],
       [ 47,  57,  41,  55],
       [ 40,  61,  55,  44],
       [ 48,  49,  48,  55],
       [105,   0,   2,  93]])

# Measurement basis definition for 9 measurements
measurements = np.array([[0.70710678+0j, 0.70710678+0j,  0.70710678+0j,  0.70710678+0j],
                         [0.70710678+0j, 0.70710678+0j,  0.70710678+0j,  0.70710678j],
                         [0.70710678+0j, 0.70710678+0j,  1+0j,0j],
                         [0.70710678+0j, 0.70710678j,    0.70710678+0j,  0.70710678+0j],
                         [0.70710678+0j, 0.70710678j,    0.70710678+0j,  0.7071067811865476j],
                         [0.70710678+0j, 0.70710678j,    1+0j,   0j],
                         [1+0j,  0j, 0.70710678+0j,  0.7071067811865476+0j],
                         [1+0j,  0j, 0.70710678+0j,  0.70710678j],
                         [1+0j, 0j, 1+0j, 0j],])

# Initiate tomography object
tomo_obj = qLib.Tomography()

# Run tomography
[rho_approx,intensity,fval] = tomo_obj.StateTomography(measurements,coincidence_counts)

# Print Results
tomo_obj.printLastOutput()
print('----------------')
bell_state = 1/np.sqrt(2) * np.array([1,0,0,1],dtype=complex)
print('Fidelity with actual : ' + str(qLib.fidelity(bell_state,rho_approx)))

State: 
0.495                -7.90e-03-i0.0111    3.59e-03+i4.92e-03   0.475-i0.0104        
-7.90e-03+i0.0111    3.12e-03             -1.80e-03-i9.49e-04  -8.15e-04+i9.50e-03  
3.59e-03-i4.92e-03   -1.80e-03+i9.49e-04  0.01                 0.0119+i1.15e-03     
0.475+i0.0104        -8.15e-04-i9.50e-03  0.0119-i1.15e-03     0.491                
intensity : 201.0
fval : 19.1
concurrence : 0.941
tangle : 0.887
entropy : 0.218
linear_entropy : 0.0587
negativity : 0.939
purity : 0.941
----------------
Fidelity with actual : 0.9693780001805247


In [2]:
rho_approx

array([[ 0.49547862+2.45418861e-19j, -0.00790412-1.11598191e-02j,
         0.00359858+4.92651856e-03j,  0.47598535-1.04056871e-02j],
       [-0.00790412+1.11598191e-02j,  0.00312356+3.51325935e-21j,
        -0.00180342-9.49890414e-04j, -0.00081527+9.50555997e-03j],
       [ 0.00359858-4.92651856e-03j, -0.00180342+9.49890414e-04j,
         0.01009115-8.26215515e-21j,  0.01196095+1.15496570e-03j],
       [ 0.47598535+1.04056871e-02j, -0.00081527-9.50555997e-03j,
         0.01196095-1.15496570e-03j,  0.49130667-2.40669965e-19j]])

In [3]:
np.linalg.eig(rho_approx)

(array([9.69890125e-01+4.92169345e-19j, 2.28341299e-02+7.44402168e-18j,
        7.27574486e-03-1.02559568e-17j, 1.70439032e-11+8.30461137e-19j]),
 array([[ 0.70850456+0.j        , -0.59589954+0.00962557j,
          0.14239983-0.22134368j,  0.27116639-0.00551651j],
        [-0.00656282+0.0150935j ,  0.18950278-0.1000812j ,
         -0.45798733+0.19826911j,  0.83948707+0.j        ],
        [ 0.011424  -0.00263074j,  0.37703241+0.31555254j,
          0.78102745+0.j        ,  0.37874025+0.06846662j],
        [ 0.70524841+0.01541611j,  0.59762588+0.j        ,
         -0.16875645+0.20780668j, -0.27081536+0.01506677j]]))