In [12]:
# dependency package: https://github.com/KwiatLab/Quantum-Tomography
import QuantumTomography as qLib
import numpy as np

# Coincidence counts for 9 measurements, XX->ZZ, 4 detectors
coincidence_counts = np.array([[428,  39, 101, 432],
       [241, 219, 324, 216],
       [245, 280, 232, 243],
       [234, 180, 308, 278],
       [ 27, 454, 508,  11],
       [225, 218, 272, 285],
       [242, 210, 290, 258],
       [221, 233, 184, 362],
       [436,  14,  66, 484]])

# Measurement basis definition for 9 measurements
measurements = np.array([[0.70710678+0j, 0.70710678+0j,  0.70710678+0j,  0.70710678+0j],
                         [0.70710678+0j, 0.70710678+0j,  0.70710678+0j,  0.70710678j],
                         [0.70710678+0j, 0.70710678+0j,  1+0j,0j],
                         [0.70710678+0j, 0.70710678j,    0.70710678+0j,  0.70710678+0j],
                         [0.70710678+0j, 0.70710678j,    0.70710678+0j,  0.7071067811865476j],
                         [0.70710678+0j, 0.70710678j,    1+0j,   0j],
                         [1+0j,  0j, 0.70710678+0j,  0.7071067811865476+0j],
                         [1+0j,  0j, 0.70710678+0j,  0.70710678j],
                         [1+0j, 0j, 1+0j, 0j],])

# Initiate tomography object
tomo_obj = qLib.Tomography()

# Run tomography
[rho_approx,intensity,fval] = tomo_obj.StateTomography(measurements,coincidence_counts)

# Print Results
tomo_obj.printLastOutput()
print('----------------')
bell_state = 1/np.sqrt(2) * np.array([1,0,0,1],dtype=complex)
print('Fidelity with actual : ' + str(qLib.fidelity(bell_state,rho_approx)))

State: 
0.429             0.0162-i0.042     -0.0165+i0.0121   0.41+i0.0136      
0.0162+i0.042     0.0235            -0.0346-i0.0138   1.19e-03+i0.0191  
-0.0165-i0.0121   -0.0346+i0.0138   0.0668            0.0203+i0.0199    
0.41-i0.0136      1.19e-03-i0.0191  0.0203-i0.0199    0.48              
intensity : 1.00e+03
fval : 112.0
concurrence : 0.756
tangle : 0.572
entropy : 0.641
linear_entropy : 0.232
negativity : 0.736
purity : 0.767
----------------
Fidelity with actual : 0.865337014118357


In [14]:
rho_approx

array([[ 0.42917078-4.87180686e-19j,  0.0162136 -4.20073770e-02j,
        -0.0165443 +1.21553200e-02j,  0.41053064+1.36874853e-02j],
       [ 0.0162136 +4.20073770e-02j,  0.02357586-2.37773200e-20j,
        -0.03460284-1.38635112e-02j,  0.00119354+1.91837806e-02j],
       [-0.0165443 -1.21553200e-02j, -0.03460284+1.38635112e-02j,
         0.0668114 -1.86593596e-20j,  0.02037094+1.99030838e-02j],
       [ 0.41053064-1.36874853e-02j,  0.00119354-1.91837806e-02j,
         0.02037094-1.99030838e-02j,  0.48044197+5.29617365e-19j]])

In [13]:
np.linalg.eig(rho_approx)

(array([8.68737411e-01+8.85547383e-18j, 1.11433326e-01+1.39134097e-17j,
        1.98292366e-02+6.87961124e-18j, 2.71746388e-08-7.09637928e-18j]),
 array([[ 0.68412015+0.02316595j, -0.27792384+0.22352928j,
          0.63289184+0.j        , -0.04235555+0.04347274j],
        [ 0.01295146+0.05068336j, -0.39754481-0.15442772j,
         -0.07722087-0.20231905j,  0.87662854+0.j        ],
        [ 0.00327227+0.00523521j,  0.74941873+0.j        ,
          0.36773981+0.27619027j,  0.43564124-0.19244878j],
        [ 0.72709579+0.j        ,  0.26884825-0.23873709j,
         -0.58364935+0.01979035j,  0.02227706+0.02285683j]]))